oc_platform_home:
    path:    /{page}
    defaults:
        _controller: OCPlateformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

oc_platform_view:
    path:    /advert/{id}
    defaults: { _controller: OCPlateformBundle:Advert:view}
    requirements:
        id: \d+

oc_platform_add:
    path:    /add
    defaults: { _controller: OCPlateformBundle:Advert:add}

oc_platform_edit:
    path:    /eddit/{id}
    defaults: { _controller: OCPlateformBundle:Advert:eddit}
    requirements:
        id: \d+

oc_platform_delete:
    path:    /delete/{id}
    defaults: { _controller: OCPlateforBundle:Advert:delete}
    requirements:
        id: \d+

oc_platform_view_slug:
    path:    /{year}/{slug}.{_format}
    defaults: { _controller: OCPlateformBundle:Advert:viewSlug}
    requirements:
        year:   \d{4}
        format: html|xml

oc_platform_profile:
    path:    /profile
    defaults: { _controller : OCPlateformBundle:Profiler:profile}