services:
#    oc_plateform.example:
#        class: OC\PlateformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
services:
    oc_platform.antispam:
        class: OC\PlateformBundle\Antispam\OCAntispam
        arguments: ["@mailer", %locale%, 50]